import type { KnowledgeItem, Report } from "../types";
import { DAY, HOUR, MINUTE, T, ago, iso } from "./clock";


export const REPORTS: Report[] = [
  {
    id: "RPT-014",
    experimentId: "EXP-104",
    workloadId: "wl_qwen_prod",
    title: "qwen-prod: p95 TTFT optimization, technical evaluation",
    status: "published",
    shareScope: "customer_link",
    methodologyVersion: "guardian-methodology v1.3",
    createdAt: iso(T.winnerPromoted + 22 * MINUTE),
    author: "Alex Chen",
    audience: "Customer platform engineering",
    artifactHash: "sha256:7c2e91d04f5ab3e8c61d9f20a4b7e5c3d18f6a90b2c4e7d1f3a5b8c0e2d4f6a1",
  },
  {
    id: "RPT-015",
    experimentId: "EXP-108",
    workloadId: "wl_qwen_prod",
    title: "INC-212 regression analysis (draft)",
    status: "draft",
    shareScope: "internal",
    methodologyVersion: "guardian-methodology v1.3",
    createdAt: iso(T.experiment108Started + 5 * MINUTE),
    author: "perf-agent v0.9.2 · Sam Okafor",
    audience: "Internal: inference platform",
    artifactHash: "pending",
  },
  {
    id: "RPT-011",
    experimentId: "EXP-091",
    workloadId: "wl_coder_batch",
    title: "coder-batch: L40S throughput per GPU-hour",
    status: "published",
    shareScope: "internal",
    methodologyVersion: "guardian-methodology v1.2",
    createdAt: ago(18 * DAY),
    author: "Riya Shah",
    audience: "FinOps + platform leads",
    artifactHash: "sha256:a07f3c5e9b1d2e4f6a8c0b3d5e7f9a1c3e5b7d9f0a2c4e6b8d0f1a3c5e7b9d2f",
  },
];

const fp = (inP50: number, inP90: number, inP99: number, outP50: number, outP90: number, outP99: number, burst: number, lc: number, greedy: number) => ({
  inputTokens: { p50: inP50, p90: inP90, p99: inP99 },
  outputTokens: { p50: outP50, p90: outP90, p99: outP99 },
  burstiness: burst,
  longContextShare: lc,
  greedyShare: greedy,
});

export const KNOWLEDGE: KnowledgeItem[] = [
  {
    id: "KN-044",
    title: "KV preemption under long-context bursts",
    workload: "qwen-prod",
    fingerprintHash: "fp_cap0918",
    bottleneck: "scheduler",
    intervention: "gpu_memory_utilization 0.80 → 0.92 (+53% KV blocks)",
    outcome: "improved",
    effect: "p95 TTFT −33.9%; capacity +18.7%",
    caveats: ["Check headroom before adding LoRA adapters.", "Replay under-represented ≥16k prompts."],
    experimentId: "EXP-104",
    recordedAt: iso(T.winnerPromoted + HOUR),
    fingerprint: fp(1190, 4900, 14800, 210, 590, 1450, 1.6, 0.012, 0.34),
  },
  {
    id: "KN-045",
    title: "Larger prefill budget trades ITL for TTFT",
    workload: "qwen-prod",
    fingerprintHash: "fp_cap0918",
    bottleneck: "prefill",
    intervention: "max_num_batched_tokens 2048 → 8192",
    outcome: "no_effect",
    effect: "p95 TTFT −28.4% but ITL p95 +14%; SLO not met",
    caveats: ["Only 8192 tested; 4096 untested."],
    experimentId: "EXP-105",
    recordedAt: iso(T.experimentsCompleted + 10 * MINUTE),
    fingerprint: fp(1190, 4900, 14800, 210, 590, 1450, 1.6, 0.012, 0.34),
  },
  {
    id: "KN-046",
    title: "Template replays inflate prefix-cache wins",
    workload: "qwen-prod",
    fingerprintHash: "fp_cap0918",
    bottleneck: "workload",
    intervention: "enable_prefix_caching on template-based replay",
    outcome: "invalid",
    effect: "Apparent −47.8% p95 TTFT; blocked by cache-integrity gate (71% hits vs 9% prod)",
    caveats: ["Use unique-prefix synthesis when testing any cache feature."],
    experimentId: "EXP-106",
    recordedAt: iso(T.experimentsCompleted + 12 * MINUTE),
    fingerprint: fp(1190, 4900, 14800, 210, 590, 1450, 1.6, 0.012, 0.34),
  },
  {
    id: "KN-039",
    title: "Chart upgrade silently dropped engine flag",
    workload: "qwen-staging",
    fingerprintHash: "fp_51c0e2aa",
    bottleneck: "scheduler",
    intervention: "Pin engine args in values.yaml; add rendered-config hash to deploy events",
    outcome: "improved",
    effect: "Restored p95 TTFT to pre-upgrade band (−24%)",
    caveats: ["Staging only; production chart lagged one version."],
    experimentId: "EXP-077",
    recordedAt: ago(23 * DAY),
    fingerprint: fp(1100, 4500, 13900, 220, 610, 1500, 1.5, 0.011, 0.36),
  },
  {
    id: "KN-031",
    title: "CUDA graphs disabled after driver change",
    workload: "coder-batch",
    fingerprintHash: "fp_0b9d7e61",
    bottleneck: "decode",
    intervention: "Re-enable CUDA graph capture (enforce_eager=false)",
    outcome: "improved",
    effect: "ITL p95 −19%",
    caveats: ["Capture adds ~40s to cold start."],
    experimentId: "EXP-058",
    recordedAt: ago(41 * DAY),
    fingerprint: fp(620, 1900, 5200, 480, 1300, 2600, 1.1, 0.0, 0.92),
  },
  {
    id: "KN-028",
    title: "Tensor parallel 2 → 4 on short prompts",
    workload: "coder-batch",
    fingerprintHash: "fp_0b9d7e61",
    bottleneck: "network",
    intervention: "tensor_parallel_size 2 → 4 (PCIe)",
    outcome: "regressed",
    effect: "Throughput per GPU −31%; all-reduce dominates on PCIe",
    caveats: ["L40S has no NVLink; result does not transfer to H100 SXM."],
    experimentId: "EXP-049",
    recordedAt: ago(52 * DAY),
    fingerprint: fp(620, 1900, 5200, 480, 1300, 2600, 1.1, 0.0, 0.92),
  },
  {
    id: "KN-022",
    title: "Speculative decoding on low-acceptance traffic",
    workload: "qwen-staging",
    fingerprintHash: "fp_51c0e2aa",
    bottleneck: "decode",
    intervention: "ngram speculative decoding (k=4)",
    outcome: "no_effect",
    effect: "Acceptance rate 0.21; ITL p95 +3% (within noise)",
    caveats: ["Chat traffic with temperature 0.7 has low n-gram overlap."],
    experimentId: "EXP-036",
    recordedAt: ago(64 * DAY),
    fingerprint: fp(1100, 4500, 13900, 220, 610, 1500, 1.5, 0.011, 0.36),
  },
];

export const PLAYBOOKS = [
  { id: "PB-03", title: "KV cache pressure", steps: ["Confirm preemptions and gpu_cache_usage_perc > 95% at peak", "Rule out a workload shift (fingerprint distance)", "Replay with +KV headroom before touching batching", "Verify engine starts with headroom ≥ 3 GiB/GPU"], uses: 4 },
  { id: "PB-07", title: "Post-deploy latency regression", steps: ["Diff rendered engine args, not only image tags", "Compare running batch vs waiting queue", "Check KV usage direction: up = memory, down = admission", "Replay current capture against previous runtime"], uses: 6 },
  { id: "PB-09", title: "Validating a cache feature", steps: ["Measure production prefix reuse from hashed prefix IDs", "Build a unique-prefix replay", "Require cache-integrity gate within 10pp", "Report hit rate next to the latency result"], uses: 2 },
];

